# Generated by Django 4.2 on 2024-06-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='prefix',
            field=models.CharField(default='uzb', max_length=5),
        ),
    ]
